/**
 * `master_table.md`, regenerated from the archive.
 *
 * ## This is the oracle
 *
 * The committed `reports/data/master_table.md` is the file every number in
 * Chapters 4 and 5 cites. It was produced by `build_master_table.py` from the
 * same logs this reads. So the output of this module must be **byte-identical**
 * to it, and `tests/replayOracle.test.ts` asserts exactly that.
 *
 * That makes the whole analysis falsifiable. If the two disagree, one of them is
 * wrong, and finding out which is the point — a plausible-looking table that
 * nothing can contradict is worth very little.
 *
 * ## Deliberate byte-for-byte mimicry
 *
 * The formatting below copies `build_master_table.py` exactly, including the
 * places where its prose is fixed rather than computed. That is not laziness:
 * an oracle only works if the two implementations are free to disagree on
 * *substance*, which means they must agree on *presentation* by construction.
 * Where this module computes something the Python hardcoded, the comment says
 * so — those are the lines the test is really exercising.
 */

import type { ArchiveRow } from "./load.ts";
import { BASELINE_RUN, CONDITIONS, FAILURE_POOL, type ConditionName, type RoundId } from "./runs.ts";
import { deriveFailureClasses } from "./classify.ts";
import {
  baselineApplyFailed,
  baselineEvaluated,
  baselineResolved,
  baselineUnresolved,
  evaluated,
  findCell,
  headline,
  logicCoverage,
  p2pBroken,
  subTestTrace,
} from "./aggregate.ts";

/** Render one experimental cell as a table entry — mirrors `fmt_cell`. */
export function fmtCell(c: ArchiveRow | null): string {
  if (c === null || !c.tests) return "not evaluated";
  const resolved = c.row.verification === "test" && c.row.resolved;
  const bits = [resolved ? "RESOLVED" : "unresolved", `F2P ${c.tests.f2pPassed}/${c.tests.f2pTotal}`];
  const broken = p2pBroken(c);
  if (broken) bits.push(`**${broken} P2P broken**`);
  return bits.join("; ");
}

export function buildMasterTable(rows: ArchiveRow[]): string {
  const L: string[] = [];
  const w = (s = "") => L.push(s);

  const classes = deriveFailureClasses(rows);
  const h = headline(rows);

  w("# Master Data Table");
  w();
  w("> Generated by `reports/data/build_master_table.py` from the `report.json` files under");
  w("> `Dissertation-main/06_Methodology/code/logs/run_evaluation/`.");
  w("> Do not edit by hand. Every number in Chapters 4 and 5 must cite this file.");
  w();
  w("Abbreviations: **F2P** = FAIL_TO_PASS (the tests the fix must make pass).");
  w("**P2P** = PASS_TO_PASS (tests that were already passing and must not break).");
  w("`RESOLVED` is SWE-bench's binary success flag: all F2P pass **and** no P2P breaks.");
  w();

  // ------------------------------------------------------------- 1. baseline
  const base = baselineEvaluated(rows);
  const resolved = baselineResolved(rows);
  const unresolved = baselineUnresolved(rows);

  w("## Table A — Baseline pilot (20 tasks, SWE-bench Lite, unified diff)");
  w();
  w("Run `day8_test`, condition `gemini-3.6-flash-blindretry-attempt1`. This is the");
  w("single-attempt baseline from which the failure pool is derived.");
  w();
  w("| # | Task | Patch applied | Outcome | F2P | P2P broken |");
  w("|---|---|---|---|---|---|");
  let n = 0;
  const sortedBase = [...base].sort((a, b) => {
    const ar = a.row.verification === "test" && a.row.resolved ? 0 : 1;
    const br = b.row.verification === "test" && b.row.resolved ? 0 : 1;
    return ar !== br ? ar - br : a.row.cell.taskId.localeCompare(b.row.cell.taskId);
  });
  for (const c of sortedBase) {
    n += 1;
    const isRes = c.row.verification === "test" && c.row.resolved;
    w(
      `| ${n} | \`${c.row.cell.taskId}\` | yes | ` +
        `${isRes ? "PASS" : "FAIL (logic)"} | ` +
        `${c.tests!.f2pPassed}/${c.tests!.f2pTotal} | ${p2pBroken(c)} |`,
    );
  }
  // DERIVED. The Python writes these four rows from a literal list, because an
  // apply failure produces no report.json for it to read. Here they come from
  // the APPLY_FAIL rows recovered in load.ts.
  for (const c of [...baselineApplyFailed(rows)].sort((a, b) =>
    a.row.cell.taskId.localeCompare(b.row.cell.taskId),
  )) {
    n += 1;
    w(`| ${n} | \`${c.row.cell.taskId}\` | **no** | ERROR (malformed patch) | n/a | n/a |`);
  }
  w();
  w(`- Resolved on first attempt: **${resolved.length}/20 = ${Math.round((100 * resolved.length) / 20)}%**`);
  w(`- Applied but failed tests (logic-class failure): **${unresolved.length}/20**`);
  // DERIVED. `4/20` is a fixed string in the Python.
  w(`- Patch never applied (format-class failure): **${baselineApplyFailed(rows).length}/20**`);
  w(
    `- **Failure pool = ${FAILURE_POOL.length} tasks** ` +
      "(`failure_pool.json`), the input to all recovery conditions.",
  );
  w();

  // -------------------------------------------------- 2. logic-class matrix
  const logic = FAILURE_POOL.filter((t) => classes.get(t) === "logic");
  w("## Table B — Recovery on logic-class failures (retrofitted patch format)");
  w();
  w("These four tasks applied cleanly at baseline and failed on test outcomes, so");
  w("they isolate reasoning ability from patch mechanics. Only runs using the");
  w("SEARCH/REPLACE representation appear here; the unified-diff runs are in Table D.");
  w();
  let head = "| Task | Baseline |";
  let sep = "|---|---|";
  for (const cond of CONDITIONS) {
    head += ` ${cond} R1 | ${cond} R2 |`;
    sep += "---|---|";
  }
  w(head);
  w(sep);
  for (const t of logic) {
    const b = findCell(rows, { run: BASELINE_RUN, taskId: t });
    let row = `| \`${t}\` | F2P ${b!.tests!.f2pPassed}/${b!.tests!.f2pTotal}`;
    row += p2pBroken(b) ? `, ${p2pBroken(b)} P2P broken |` : " |";
    for (const condition of CONDITIONS) {
      for (const round of ["R1", "R2"] as RoundId[]) {
        row += ` ${fmtCell(findCell(rows, { taskId: t, condition, round, format: "sr" }))} |`;
      }
    }
    w(row);
  }
  w();

  // coverage accounting
  const cov = logicCoverage(rows, logic);
  w("### Coverage of Table B");
  w();
  w("| Condition | R1 cells evaluated | R2 cells evaluated | Total of 8 |");
  w("|---|---|---|---|");
  for (const c of cov.per) {
    w(`| ${c.condition} | ${c.r1}/4 | ${c.r2}/4 | ${c.total}/8 |`);
  }
  w(`| **All** | | | **${cov.evaluatedCells}/${cov.totalCells}** |`);
  w();
  w(
    `**${cov.evaluatedCells} of ${cov.totalCells} logic-class cells were evaluated; ` +
      `${cov.totalCells - cov.evaluatedCells} were never run.** The missing cells are a consequence of the`,
  );
  w("20-request/day free-tier quota documented in `data/config.md`, not of a");
  w("selection decision. Chapter 5 must report this coverage alongside any claim");
  w("of consistency across conditions or rounds.");
  w();

  // ------------------------------------------------- 3. format-class matrix
  const fmtTasks = FAILURE_POOL.filter((t) => classes.get(t) === "format");
  w("## Table C — Recovery on format-class failures");
  w();
  w("These four tasks failed at baseline because the generated unified diff could");
  w("not be applied at all. No claim about reasoning can be made from them until");
  w("the patch representation is fixed; that is exactly what the retrofit tests.");
  w();
  w("| Task | Blind Retry | Reflection-only | Diagnose+Revise | Patch format | Note |");
  w("|---|---|---|---|---|---|");
  for (const t of fmtTasks) {
    const got = evaluated(rows).filter((r) => r.row.cell.taskId === t);
    if (got.length === 0) {
      w(
        `| \`${t}\` | excluded | excluded | excluded | n/a | ` +
          "**RECITATION** — generation blocked, see §4.18 |",
      );
      continue;
    }
    let row = `| \`${t}\` |`;
    for (const condition of CONDITIONS) {
      const hits = got.filter((c) => c.condition === condition);
      row += ` ${hits.length > 0 ? fmtCell(hits[0]!) : "not evaluated"} |`;
    }
    const fmts = [...new Set(got.map((c) => c.format))].sort();
    const srOnly = fmts.length === 1 && fmts[0] === "sr";
    row += srOnly ? " SEARCH/REPLACE |" : " unified diff |";
    row += srOnly ? " retrofitted, verified |" : " pre-retrofit; L1/L2 skipped for quota |";
    w(row);
  }
  w();

  // ---------------------------------------------------- 4. superseded runs
  w("## Table D — Superseded unified-diff recovery runs");
  w();
  w("Retained for completeness and for the audit trail. These runs predate the");
  w("patch-representation retrofit, so they are **not** comparable with Table B and");
  w("must not be pooled with it.");
  w();
  w("| Run | Condition | Task | Outcome | F2P | P2P broken |");
  w("|---|---|---|---|---|---|");
  const superseded = evaluated(rows)
    .filter((c) => c.format === "diff" && c.run !== BASELINE_RUN)
    .sort((a, b) => a.run.localeCompare(b.run) || a.row.cell.taskId.localeCompare(b.row.cell.taskId));
  for (const c of superseded) {
    const isRes = c.row.verification === "test" && c.row.resolved;
    w(
      `| \`${c.run}\` | ${c.condition} | \`${c.row.cell.taskId}\` | ` +
        `${isRes ? "RESOLVED" : "unresolved"} | ` +
        `${c.tests!.f2pPassed}/${c.tests!.f2pTotal} | ${p2pBroken(c)} |`,
    );
  }
  w();

  // ------------------------------------------------------ 5. headline stats
  w("## Table E — Headline figures");
  w();
  w("| Quantity | Value |");
  w("|---|---|");
  w(`| Baseline resolve rate | ${h.baselineResolved}/20 = ${Math.round(h.baselinePct)}% |`);
  w(`| Failure pool | ${h.poolSize} tasks |`);
  w(`| Pool tasks with at least one evaluated recovery attempt | ${h.evaluable}/${h.poolSize} |`);
  w(`| Pool tasks excluded outright | 1 (\`astropy__astropy-14182\`, RECITATION) |`);
  w(`| Pool tasks recovered by any condition | **${h.recovered.length}/${h.evaluable}** |`);
  w(`| — of which logic-class | **${h.recoveredLogic.length}/${h.logicTasks.length}** |`);
  w(`| — of which format-class | **${h.recoveredFormat.length}/${h.formatTasksEvaluable.length}** |`);
  w();
  w("### The two findings this table supports");
  w();
  w("**Finding 1 — recovery succeeded only where the failure was mechanical.**");
  w(`Every recovery observed in this study (${h.recovered.map((t) => "`" + t + "`").join(", ")})`);
  w("was a format-class failure whose patch representation had been repaired. Not one");
  w("of the four logic-class failures was resolved by any strategy in any round.");
  w("Changing *how the edit was expressed* moved outcomes; changing *what the model");
  w("was told about its failure* did not.");
  w();
  w("**Finding 2 — richer post-failure information produced identical outcomes.**");
  w("On `django__django-11019` the sub-test score is identical under all three");
  w("strategies and both rounds:");
  w();
  w("| Condition / round | F2P | P2P broken |");
  w("|---|---|---|");
  for (const t of subTestTrace(rows, "django__django-11019")) {
    w(`| ${t.label} | ${t.f2pPassed}/${t.f2pTotal} | ${t.p2pBroken} |`);
  }
  w();
  w("The retrofit alone moved this task from 0/16 with 33 regressions to 6/16 with");
  w("none. Reflection and diagnosis then added nothing on top of blind retry, while");
  w("costing roughly three times the input tokens (`data/config.md`).");
  w();
  const d = findCell(rows, {
    taskId: "django__django-11283",
    condition: "Diagnose+Revise" as ConditionName,
    round: "R1",
    format: "sr",
  });
  if (d && p2pBroken(d)) {
    w("**Counter-signal worth reporting.** On `django__django-11283`, Diagnose+Revise");
    w(`broke **${p2pBroken(d)} PASS_TO_PASS tests** where Blind Retry broke none.`);
    w("On this task the additional diagnostic context made the patch more damaging,");
    w("not less. Chapter 5 should report this rather than average it away.");
    w();
  }

  w("---");
  w();
  w(
    `*Regenerated from ${evaluated(rows).length} evaluation records across ` +
      `${new Set(evaluated(rows).map((c) => c.run)).size} runs.*`,
  );

  return L.join("\n") + "\n";
}
