/**
 * The four conditions.
 *
 * Each is a few lines, because each *is* only a few lines: a choice of what
 * goes into the prompt. That is the manipulated variable of the study, and
 * confining every condition to this file makes the whole difference between
 * them readable at once.
 *
 * Names match the dissertation's Table A so a reader can line them up:
 *
 *   l0_baseline           Baseline          the first attempt, no recovery
 *   l1_blind_retry        Blind Retry       try again, shown nothing new
 *   l2_reflection         Reflection-only   + its own previous attempt
 *   l2_5_diagnose_revise  Diagnose+Revise   + real evidence of what went wrong
 */

import { buildPrompt } from "./prompt.ts";
import type { Strategy, StrategyContext, StrategyPlan } from "./types.ts";

/**
 * The most recent round that actually said something.
 *
 * Not simply `history.at(-1)`. A round whose condition was refused, whose
 * budget was spent, or whose provider failed still records an attempt — that is
 * the no-holes guarantee — but its response is empty. Reflecting on an empty
 * response would render a prompt that announces "Here was your PREVIOUS
 * ATTEMPT:" above nothing, which is the same dishonesty as an empty evidence
 * block (D22): the prompt would assert something false to the model.
 *
 * Scanning backwards rather than taking the last also means a transient
 * provider failure in round 2 does not destroy round 3's ability to reflect on
 * round 1.
 */
function lastRealAttempt(ctx: StrategyContext) {
  for (let i = ctx.history.length - 1; i >= 0; i--) {
    const a = ctx.history[i]!;
    if (a.response.trim() !== "") return a;
  }
  return undefined;
}

/** Shared prompt inputs. Identical across conditions by construction. */
function base(ctx: StrategyContext) {
  return {
    repo: ctx.task.repo,
    problemStatement: ctx.task.problemStatement,
    filePath: ctx.filePath,
    fileContent: ctx.fileContent,
  };
}

/**
 * Baseline — the first attempt, with no prior to reflect on.
 *
 * Runnable, and it has to be. Step 5 made this replay-only on the grounds that
 * Chapter 5's baseline numbers are already definitive: 12/20 resolved, verified
 * in Docker, regenerated byte-identically by step 3. That reasoning was right
 * about *replication* and wrong about everything else, and the first live sweep
 * proved it — **16 of 24 cells could not run**, because Reflection-only and
 * Diagnose+Revise need a previous attempt and the grid gave them none (D26).
 *
 * In the original the prior was the baseline: `day8_test` is round R0, and each
 * condition's R1 reflected on it. So a baseline that cannot run makes two of
 * the three recovery conditions structurally unreachable.
 *
 * The prompt is format-dependent, and both come from the study itself:
 *
 *   unified_diff    `day7_step1_generate_full_pilot.py` — asks for a diff in a
 *                   `PATCH:` section, and instructs the model that hunk counts
 *                   must match exactly (the defect D14 measured it failing).
 *   search_replace  the blind-retry prompt, which *is* a first-attempt prompt:
 *                   it shows the problem and the file and no history.
 *
 * What remains replay-only is the *claim*: a baseline run here is a new
 * measurement, not a reproduction of Chapter 5's 12/20, because it cannot run
 * tests (D6). `bun run replay` is still the source of the submitted numbers.
 */
export const baseline: Strategy = {
  id: "l0_baseline",
  label: "Baseline",
  needsHistory: false,
  needsEvidence: false,
  async plan(ctx: StrategyContext): Promise<StrategyPlan> {
    const { prompt, sourceFile, sourceSha256 } = await buildPrompt(
      "l0_baseline",
      base(ctx),
      ctx.cell.editFormat,
    );
    return {
      runnable: true,
      prompt,
      promptSource: sourceFile,
      promptSha256: sourceSha256,
    };
  },
};

/**
 * Blind Retry — a fresh attempt with no new information.
 *
 * Worth noting what "blind" means here, because it is easy to misread: the
 * model is not shown its previous attempt at all. The prompt is identical to a
 * first attempt. So this condition measures how much of recovery is explained
 * by sampling variance alone — which is exactly the right control, and
 * stronger than showing the model its failure without telling it why.
 */
export const blindRetry: Strategy = {
  id: "l1_blind_retry",
  label: "Blind Retry",
  needsHistory: false,
  needsEvidence: false,
  async plan(ctx: StrategyContext): Promise<StrategyPlan> {
    const { prompt, sourceFile, sourceSha256 } = await buildPrompt(
      "l1_blind_retry",
      base(ctx),
      ctx.cell.editFormat,
    );
    return {
      runnable: true,
      prompt,
      promptSource: sourceFile,
      promptSha256: sourceSha256,
    };
  },
};

/**
 * Reflection-only — shown its previous attempt, told it failed, told nothing
 * about why.
 *
 * The prompt asserts the previous attempt "did NOT resolve the issue". For
 * that to be true the cell must actually have a previous attempt, so a missing
 * history is refused rather than filled with a fresh prompt: running L1's
 * prompt and labelling it L2 would collapse the two conditions being compared.
 */
export const reflection: Strategy = {
  id: "l2_reflection",
  label: "Reflection-only",
  needsHistory: true,
  needsEvidence: false,
  async plan(ctx: StrategyContext): Promise<StrategyPlan> {
    const previous = lastRealAttempt(ctx);
    if (!previous) {
      return {
        runnable: false,
        reason:
          "l2_reflection needs a previous attempt to reflect on, and no earlier " +
          "round produced a response. Round 1 must run, and succeed in " +
          "answering, before round 2.",
      };
    }
    const { prompt, sourceFile, sourceSha256 } = await buildPrompt(
      "l2_reflection",
      { ...base(ctx), previousAttempt: previous.response },
      ctx.cell.editFormat,
    );
    return {
      runnable: true,
      prompt,
      promptSource: sourceFile,
      promptSha256: sourceSha256,
    };
  },
};

/**
 * Diagnose+Revise — Reflection-only plus real evidence of the failure.
 *
 * The one condition that can be unrunnable for a reason that is not about the
 * model. Its prompt tells the model it is receiving "the REAL, ACTUAL result
 * of running your previous patch against the real test suite (ground truth,
 * not a guess)". Without Docker (D6) that sentence can only be honoured from
 * the archive, or weakened to git's apply error.
 *
 * `evidence.ts` resolves which, and labels it. This strategy refuses `none`
 * outright: a Diagnose+Revise prompt with an empty evidence block is a
 * Reflection-only prompt that lies to the model about what it contains.
 */
export const diagnoseRevise: Strategy = {
  id: "l2_5_diagnose_revise",
  label: "Diagnose+Revise",
  needsHistory: true,
  needsEvidence: true,
  async plan(ctx: StrategyContext): Promise<StrategyPlan> {
    const previous = lastRealAttempt(ctx);
    if (!previous) {
      return {
        runnable: false,
        reason:
          "l2_5_diagnose_revise needs a previous attempt to diagnose, and no " +
          "earlier round produced a response.",
      };
    }
    if (ctx.evidence.source === "none") {
      return {
        runnable: false,
        reason:
          "l2_5_diagnose_revise needs real evidence of the previous failure " +
          "and none is available. Test output requires Docker, which this " +
          "pipeline does not use (D6); an apply error exists only when the " +
          "patch was rejected. Running without evidence would make this " +
          "condition indistinguishable from Reflection-only (D22).",
      };
    }
    const { prompt, sourceFile, sourceSha256 } = await buildPrompt(
      "l2_5_diagnose_revise",
      {
        ...base(ctx),
        previousAttempt: previous.response,
        evidence: ctx.evidence.text,
      },
      ctx.cell.editFormat,
    );
    return {
      runnable: true,
      prompt,
      promptSource: sourceFile,
      promptSha256: sourceSha256,
    };
  },
};

export const STRATEGIES = {
  l0_baseline: baseline,
  l1_blind_retry: blindRetry,
  l2_reflection: reflection,
  l2_5_diagnose_revise: diagnoseRevise,
} as const;

export type ImplementedStrategyId = keyof typeof STRATEGIES;

export function getStrategy(id: string): Strategy {
  const s = (STRATEGIES as Record<string, Strategy | undefined>)[id];
  if (!s) {
    throw new Error(
      `strategy "${id}" is not implemented. Implemented: ` +
        `${Object.keys(STRATEGIES).join(", ")}. l3_constrained and ` +
        `l4_tool_grounded are declared in core/types.ts and belong to step 8.`,
    );
  }
  return s;
}
