/**
 * Audits the 61 model patches preserved in the archive, using the *tested*
 * validator rather than a throwaway script.
 *
 *   bun scripts/audit_legacy_patches.ts
 *
 * This produces the format finding as a measured number, offline, from committed
 * data, with no API call. The patches are real pre-retrofit model output from
 * `archive/legacy_predictions/*.json` — `model_patch` per instance — which is the
 * only surviving trace of what the models actually wrote, since `attempts/` is
 * gone (D0).
 *
 * The archive payload is gitignored, because every file in it already exists
 * upstream at `Lagadnakul/Dissertation@c8872d0`. So **the derived result must be
 * committed or it is lost**: this writes `data/legacy_patch_audit.json`, which
 * `tests/legacyPatches.test.ts` then checks even on a machine with no archive.
 *
 * A first attempt at this analysis reported 3/51 clean, because it counted the
 * trailing "" from `split("\n")` as a body line and so flagged every patch —
 * including the programmatically generated ones known to have applied. That is
 * exactly why the logic now lives in `validateDiff` with tests around it, and why
 * `MISCOUNT_WARNING` below exists.
 */

import { readdir } from "node:fs/promises";
import { join } from "node:path";
import { validateDiff, diffFiles } from "../packages/pipeline/edits/unified.ts";
import type { MalformedReason } from "@rb/core";

const PRED_DIR = "archive/legacy_predictions";
const OUT = "data/legacy_patch_audit.json";
const UPSTREAM = "Lagadnakul/Dissertation@c8872d070fb0b098394796dfbc68bcf67c3bd957";

/**
 * If this ever trips, the validator has regressed: patches generated by
 * `difflib.unified_diff` are valid by construction, so a defect in that era means
 * the analysis is measuring our code rather than the models.
 */
const MISCOUNT_WARNING =
  "programmatically generated patches reported defects — the validator is wrong, " +
  "not the patches. Investigate before citing any number from this run.";

interface Row {
  file: string;
  instanceId: string;
  model: string;
  /** "search_replace" once the retrofit landed, else "unified_diff". */
  era: "unified_diff" | "search_replace";
  chars: number;
  hunks: number;
  files: string[];
  reasons: MalformedReason[];
  details: string[];
}

const preds = (await readdir(PRED_DIR)).filter((f) => f.endsWith(".json")).sort();
if (preds.length === 0) {
  console.error(
    `no prediction files in ${PRED_DIR}/.\n` +
      `The archive payload is gitignored; rebuild it from ${UPSTREAM}.`,
  );
  process.exit(1);
}

const rows: Row[] = [];
for (const file of preds) {
  const entries = (await Bun.file(join(PRED_DIR, file)).json()) as {
    instance_id: string;
    model_patch: string;
    model_name_or_path: string;
  }[];

  for (const e of entries) {
    const defects = validateDiff(e.model_patch);
    rows.push({
      file,
      instanceId: e.instance_id,
      model: e.model_name_or_path,
      // The retrofit is identifiable from the model label the original wrote.
      era: e.model_name_or_path.includes("searchreplace") ? "search_replace" : "unified_diff",
      chars: e.model_patch.length,
      hunks: (e.model_patch.match(/^@@ /gm) ?? []).length,
      files: diffFiles(e.model_patch),
      reasons: defects.map((d) => d.reason),
      details: defects.map((d) => d.detail),
    });
  }
}

// ------------------------------------------------------------------ summarise

type Summary = {
  patches: number;
  clean: number;
  cleanPct: number;
  reasonCounts: Record<string, number>;
  patchesWithDefect: number;
};

function summarise(group: Row[]): Summary {
  const clean = group.filter((r) => r.reasons.length === 0).length;
  const reasonCounts: Record<string, number> = {};
  for (const r of group) {
    // Count each reason once per patch, so one patch with three bad hunks does
    // not outweigh three patches with one each.
    for (const reason of new Set(r.reasons)) {
      reasonCounts[reason] = (reasonCounts[reason] ?? 0) + 1;
    }
  }
  return {
    patches: group.length,
    clean,
    cleanPct: group.length === 0 ? 0 : Math.round((1000 * clean) / group.length) / 10,
    reasonCounts,
    patchesWithDefect: group.length - clean,
  };
}

const byEra = {
  unified_diff: summarise(rows.filter((r) => r.era === "unified_diff")),
  search_replace: summarise(rows.filter((r) => r.era === "search_replace")),
};

const warnings: string[] = [];
if (byEra.search_replace.patches > 0 && byEra.search_replace.clean !== byEra.search_replace.patches) {
  warnings.push(MISCOUNT_WARNING);
}

const audit = {
  generated_at: new Date().toISOString(),
  generated_by: "scripts/audit_legacy_patches.ts",
  source: { dir: PRED_DIR, upstream: UPSTREAM, files: preds },
  method:
    "validateDiff() from packages/pipeline/edits/unified.ts — structural defects " +
    "detectable without the source file: missing file header, unparseable hunk " +
    "header, declared @@ counts disagreeing with the hunk body. Not a substitute " +
    "for git apply, which additionally checks that the context exists (D13).",
  totals: { patches: rows.length, by_era: byEra },
  warnings,
  rows,
};

await Bun.write(OUT, JSON.stringify(audit, null, 2) + "\n");

// ---------------------------------------------------------------------- print

const pad = (s: string, n: number) => s.padEnd(n);
console.log(`\nlegacy patch audit — ${rows.length} patches from ${preds.length} files\n`);
for (const [era, s] of Object.entries(byEra)) {
  const label = era === "unified_diff" ? "model wrote the diff" : "difflib wrote the diff";
  console.log(`${pad(era, 16)} ${pad(label, 24)} ${s.clean}/${s.patches} clean (${s.cleanPct}%)`);
  for (const [reason, n] of Object.entries(s.reasonCounts).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${String(n).padStart(4)}  ${reason}`);
  }
}
for (const w of warnings) console.log(`\nWARNING: ${w}`);
console.log(`\nwrote ${OUT}`);
